// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESSAGES/message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_MESSAGES_2fmessage_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MESSAGES_2fmessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_start_time;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MESSAGES_2fmessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_task;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MESSAGES_2fmessage_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_tasks_set_pro_cpu;
}  // namespace protobuf_MESSAGES_2fmessage_2eproto
namespace Message {
namespace protobuf {
class scheduleDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<schedule>
      _instance;
} _schedule_default_instance_;
class tasks_set_pro_cpuDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<tasks_set_pro_cpu>
      _instance;
} _tasks_set_pro_cpu_default_instance_;
class taskDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<task>
      _instance;
} _task_default_instance_;
class start_timeDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<start_time>
      _instance;
} _start_time_default_instance_;
class Job_gangDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Job_gang>
      _instance;
} _Job_gang_default_instance_;
}  // namespace protobuf
}  // namespace Message
namespace protobuf_MESSAGES_2fmessage_2eproto {
static void InitDefaultsschedule() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_schedule_default_instance_;
    new (ptr) ::Message::protobuf::schedule();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::schedule::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_schedule =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsschedule}, {
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_tasks_set_pro_cpu.base,
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_start_time.base,}};

static void InitDefaultstasks_set_pro_cpu() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_tasks_set_pro_cpu_default_instance_;
    new (ptr) ::Message::protobuf::tasks_set_pro_cpu();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::tasks_set_pro_cpu::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_tasks_set_pro_cpu =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultstasks_set_pro_cpu}, {
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_task.base,}};

static void InitDefaultstask() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_task_default_instance_;
    new (ptr) ::Message::protobuf::task();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::task::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_task =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultstask}, {}};

static void InitDefaultsstart_time() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_start_time_default_instance_;
    new (ptr) ::Message::protobuf::start_time();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::start_time::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_start_time =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsstart_time}, {}};

static void InitDefaultsJob_gang() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_Job_gang_default_instance_;
    new (ptr) ::Message::protobuf::Job_gang();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::Job_gang::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Job_gang =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsJob_gang}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_schedule.base);
  ::google::protobuf::internal::InitSCC(&scc_info_tasks_set_pro_cpu.base);
  ::google::protobuf::internal::InitSCC(&scc_info_task.base);
  ::google::protobuf::internal::InitSCC(&scc_info_start_time.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Job_gang.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::schedule, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::schedule, tasksets_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::schedule, start_time_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::tasks_set_pro_cpu, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::tasks_set_pro_cpu, tasks_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::task, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::task, task_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::task, duration_ms_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::task, path_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::start_time, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::start_time, sec_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::start_time, ms_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, requested_processors_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, job_path_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Message::protobuf::schedule)},
  { 7, -1, sizeof(::Message::protobuf::tasks_set_pro_cpu)},
  { 13, -1, sizeof(::Message::protobuf::task)},
  { 21, -1, sizeof(::Message::protobuf::start_time)},
  { 28, -1, sizeof(::Message::protobuf::Job_gang)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_schedule_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_tasks_set_pro_cpu_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_task_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_start_time_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_Job_gang_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MESSAGES/message.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026MESSAGES/message.proto\022\020Message.protob"
      "uf\"s\n\010schedule\0225\n\010tasksets\030\001 \003(\0132#.Messa"
      "ge.protobuf.tasks_set_pro_cpu\0220\n\nstart_t"
      "ime\030\002 \001(\0132\034.Message.protobuf.start_time\""
      ":\n\021tasks_set_pro_cpu\022%\n\005tasks\030\003 \003(\0132\026.Me"
      "ssage.protobuf.task\":\n\004task\022\017\n\007task_id\030\004"
      " \001(\t\022\023\n\013duration_ms\030\005 \001(\005\022\014\n\004path\030\006 \001(\t\""
      "%\n\nstart_time\022\013\n\003sec\030\007 \001(\003\022\n\n\002ms\030\010 \001(\003\"J"
      "\n\010Job_gang\022\016\n\006job_id\030\t \001(\005\022\034\n\024requested_"
      "processors\030\n \001(\005\022\020\n\010job_path\030\013 \001(\tb\006prot"
      "o3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 402);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MESSAGES/message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MESSAGES_2fmessage_2eproto
namespace Message {
namespace protobuf {

// ===================================================================

void schedule::InitAsDefaultInstance() {
  ::Message::protobuf::_schedule_default_instance_._instance.get_mutable()->start_time_ = const_cast< ::Message::protobuf::start_time*>(
      ::Message::protobuf::start_time::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int schedule::kTasksetsFieldNumber;
const int schedule::kStartTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

schedule::schedule()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_schedule.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.schedule)
}
schedule::schedule(const schedule& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      tasksets_(from.tasksets_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_start_time()) {
    start_time_ = new ::Message::protobuf::start_time(*from.start_time_);
  } else {
    start_time_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.schedule)
}

void schedule::SharedCtor() {
  start_time_ = NULL;
}

schedule::~schedule() {
  // @@protoc_insertion_point(destructor:Message.protobuf.schedule)
  SharedDtor();
}

void schedule::SharedDtor() {
  if (this != internal_default_instance()) delete start_time_;
}

void schedule::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* schedule::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const schedule& schedule::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_schedule.base);
  return *internal_default_instance();
}


void schedule::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.schedule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tasksets_.Clear();
  if (GetArenaNoVirtual() == NULL && start_time_ != NULL) {
    delete start_time_;
  }
  start_time_ = NULL;
  _internal_metadata_.Clear();
}

bool schedule::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.schedule)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Message.protobuf.tasks_set_pro_cpu tasksets = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_tasksets()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .Message.protobuf.start_time start_time = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_start_time()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.schedule)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.schedule)
  return false;
#undef DO_
}

void schedule::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.schedule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.tasks_set_pro_cpu tasksets = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasksets_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->tasksets(static_cast<int>(i)),
      output);
  }

  // .Message.protobuf.start_time start_time = 2;
  if (this->has_start_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->_internal_start_time(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.schedule)
}

::google::protobuf::uint8* schedule::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.schedule)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.tasks_set_pro_cpu tasksets = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasksets_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->tasksets(static_cast<int>(i)), deterministic, target);
  }

  // .Message.protobuf.start_time start_time = 2;
  if (this->has_start_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->_internal_start_time(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.schedule)
  return target;
}

size_t schedule::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.schedule)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Message.protobuf.tasks_set_pro_cpu tasksets = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->tasksets_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->tasksets(static_cast<int>(i)));
    }
  }

  // .Message.protobuf.start_time start_time = 2;
  if (this->has_start_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *start_time_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void schedule::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.schedule)
  GOOGLE_DCHECK_NE(&from, this);
  const schedule* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const schedule>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.schedule)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.schedule)
    MergeFrom(*source);
  }
}

void schedule::MergeFrom(const schedule& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.schedule)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tasksets_.MergeFrom(from.tasksets_);
  if (from.has_start_time()) {
    mutable_start_time()->::Message::protobuf::start_time::MergeFrom(from.start_time());
  }
}

void schedule::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.schedule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void schedule::CopyFrom(const schedule& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.schedule)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool schedule::IsInitialized() const {
  return true;
}

void schedule::Swap(schedule* other) {
  if (other == this) return;
  InternalSwap(other);
}
void schedule::InternalSwap(schedule* other) {
  using std::swap;
  CastToBase(&tasksets_)->InternalSwap(CastToBase(&other->tasksets_));
  swap(start_time_, other->start_time_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata schedule::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void tasks_set_pro_cpu::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tasks_set_pro_cpu::kTasksFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tasks_set_pro_cpu::tasks_set_pro_cpu()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_tasks_set_pro_cpu.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.tasks_set_pro_cpu)
}
tasks_set_pro_cpu::tasks_set_pro_cpu(const tasks_set_pro_cpu& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      tasks_(from.tasks_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.tasks_set_pro_cpu)
}

void tasks_set_pro_cpu::SharedCtor() {
}

tasks_set_pro_cpu::~tasks_set_pro_cpu() {
  // @@protoc_insertion_point(destructor:Message.protobuf.tasks_set_pro_cpu)
  SharedDtor();
}

void tasks_set_pro_cpu::SharedDtor() {
}

void tasks_set_pro_cpu::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* tasks_set_pro_cpu::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tasks_set_pro_cpu& tasks_set_pro_cpu::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_tasks_set_pro_cpu.base);
  return *internal_default_instance();
}


void tasks_set_pro_cpu::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.tasks_set_pro_cpu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tasks_.Clear();
  _internal_metadata_.Clear();
}

bool tasks_set_pro_cpu::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.tasks_set_pro_cpu)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Message.protobuf.task tasks = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_tasks()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.tasks_set_pro_cpu)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.tasks_set_pro_cpu)
  return false;
#undef DO_
}

void tasks_set_pro_cpu::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.tasks_set_pro_cpu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.task tasks = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasks_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3,
      this->tasks(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.tasks_set_pro_cpu)
}

::google::protobuf::uint8* tasks_set_pro_cpu::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.tasks_set_pro_cpu)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.task tasks = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasks_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, this->tasks(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.tasks_set_pro_cpu)
  return target;
}

size_t tasks_set_pro_cpu::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.tasks_set_pro_cpu)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Message.protobuf.task tasks = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->tasks_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->tasks(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void tasks_set_pro_cpu::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.tasks_set_pro_cpu)
  GOOGLE_DCHECK_NE(&from, this);
  const tasks_set_pro_cpu* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tasks_set_pro_cpu>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.tasks_set_pro_cpu)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.tasks_set_pro_cpu)
    MergeFrom(*source);
  }
}

void tasks_set_pro_cpu::MergeFrom(const tasks_set_pro_cpu& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.tasks_set_pro_cpu)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tasks_.MergeFrom(from.tasks_);
}

void tasks_set_pro_cpu::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.tasks_set_pro_cpu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tasks_set_pro_cpu::CopyFrom(const tasks_set_pro_cpu& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.tasks_set_pro_cpu)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tasks_set_pro_cpu::IsInitialized() const {
  return true;
}

void tasks_set_pro_cpu::Swap(tasks_set_pro_cpu* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tasks_set_pro_cpu::InternalSwap(tasks_set_pro_cpu* other) {
  using std::swap;
  CastToBase(&tasks_)->InternalSwap(CastToBase(&other->tasks_));
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata tasks_set_pro_cpu::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void task::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int task::kTaskIdFieldNumber;
const int task::kDurationMsFieldNumber;
const int task::kPathFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

task::task()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_task.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.task)
}
task::task(const task& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  task_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.task_id().size() > 0) {
    task_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.task_id_);
  }
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.path().size() > 0) {
    path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.path_);
  }
  duration_ms_ = from.duration_ms_;
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.task)
}

void task::SharedCtor() {
  task_id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  duration_ms_ = 0;
}

task::~task() {
  // @@protoc_insertion_point(destructor:Message.protobuf.task)
  SharedDtor();
}

void task::SharedDtor() {
  task_id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void task::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* task::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const task& task::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_task.base);
  return *internal_default_instance();
}


void task::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  task_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  duration_ms_ = 0;
  _internal_metadata_.Clear();
}

bool task::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.task)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string task_id = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_task_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->task_id().data(), static_cast<int>(this->task_id().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.protobuf.task.task_id"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 duration_ms = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &duration_ms_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string path = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->path().data(), static_cast<int>(this->path().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.protobuf.task.path"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.task)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.task)
  return false;
#undef DO_
}

void task::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string task_id = 4;
  if (this->task_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->task_id().data(), static_cast<int>(this->task_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.task.task_id");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->task_id(), output);
  }

  // int32 duration_ms = 5;
  if (this->duration_ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->duration_ms(), output);
  }

  // string path = 6;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), static_cast<int>(this->path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.task.path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->path(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.task)
}

::google::protobuf::uint8* task::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.task)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string task_id = 4;
  if (this->task_id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->task_id().data(), static_cast<int>(this->task_id().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.task.task_id");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->task_id(), target);
  }

  // int32 duration_ms = 5;
  if (this->duration_ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->duration_ms(), target);
  }

  // string path = 6;
  if (this->path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->path().data(), static_cast<int>(this->path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.task.path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->path(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.task)
  return target;
}

size_t task::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.task)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string task_id = 4;
  if (this->task_id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->task_id());
  }

  // string path = 6;
  if (this->path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->path());
  }

  // int32 duration_ms = 5;
  if (this->duration_ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->duration_ms());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void task::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.task)
  GOOGLE_DCHECK_NE(&from, this);
  const task* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const task>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.task)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.task)
    MergeFrom(*source);
  }
}

void task::MergeFrom(const task& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.task)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.task_id().size() > 0) {

    task_id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.task_id_);
  }
  if (from.path().size() > 0) {

    path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.path_);
  }
  if (from.duration_ms() != 0) {
    set_duration_ms(from.duration_ms());
  }
}

void task::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.task)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void task::CopyFrom(const task& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.task)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool task::IsInitialized() const {
  return true;
}

void task::Swap(task* other) {
  if (other == this) return;
  InternalSwap(other);
}
void task::InternalSwap(task* other) {
  using std::swap;
  task_id_.Swap(&other->task_id_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  path_.Swap(&other->path_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(duration_ms_, other->duration_ms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata task::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void start_time::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int start_time::kSecFieldNumber;
const int start_time::kMsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

start_time::start_time()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_start_time.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.start_time)
}
start_time::start_time(const start_time& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&sec_, &from.sec_,
    static_cast<size_t>(reinterpret_cast<char*>(&ms_) -
    reinterpret_cast<char*>(&sec_)) + sizeof(ms_));
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.start_time)
}

void start_time::SharedCtor() {
  ::memset(&sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ms_) -
      reinterpret_cast<char*>(&sec_)) + sizeof(ms_));
}

start_time::~start_time() {
  // @@protoc_insertion_point(destructor:Message.protobuf.start_time)
  SharedDtor();
}

void start_time::SharedDtor() {
}

void start_time::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* start_time::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const start_time& start_time::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_start_time.base);
  return *internal_default_instance();
}


void start_time::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.start_time)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&sec_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&ms_) -
      reinterpret_cast<char*>(&sec_)) + sizeof(ms_));
  _internal_metadata_.Clear();
}

bool start_time::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.start_time)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int64 sec = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(56u /* 56 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &sec_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int64 ms = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &ms_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.start_time)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.start_time)
  return false;
#undef DO_
}

void start_time::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.start_time)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sec = 7;
  if (this->sec() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(7, this->sec(), output);
  }

  // int64 ms = 8;
  if (this->ms() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(8, this->ms(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.start_time)
}

::google::protobuf::uint8* start_time::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.start_time)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int64 sec = 7;
  if (this->sec() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(7, this->sec(), target);
  }

  // int64 ms = 8;
  if (this->ms() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(8, this->ms(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.start_time)
  return target;
}

size_t start_time::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.start_time)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int64 sec = 7;
  if (this->sec() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->sec());
  }

  // int64 ms = 8;
  if (this->ms() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int64Size(
        this->ms());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void start_time::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.start_time)
  GOOGLE_DCHECK_NE(&from, this);
  const start_time* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const start_time>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.start_time)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.start_time)
    MergeFrom(*source);
  }
}

void start_time::MergeFrom(const start_time& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.start_time)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sec() != 0) {
    set_sec(from.sec());
  }
  if (from.ms() != 0) {
    set_ms(from.ms());
  }
}

void start_time::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.start_time)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void start_time::CopyFrom(const start_time& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.start_time)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool start_time::IsInitialized() const {
  return true;
}

void start_time::Swap(start_time* other) {
  if (other == this) return;
  InternalSwap(other);
}
void start_time::InternalSwap(start_time* other) {
  using std::swap;
  swap(sec_, other->sec_);
  swap(ms_, other->ms_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata start_time::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Job_gang::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Job_gang::kJobIdFieldNumber;
const int Job_gang::kRequestedProcessorsFieldNumber;
const int Job_gang::kJobPathFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Job_gang::Job_gang()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_Job_gang.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.Job_gang)
}
Job_gang::Job_gang(const Job_gang& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  job_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.job_path().size() > 0) {
    job_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.job_path_);
  }
  ::memcpy(&job_id_, &from.job_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&requested_processors_) -
    reinterpret_cast<char*>(&job_id_)) + sizeof(requested_processors_));
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.Job_gang)
}

void Job_gang::SharedCtor() {
  job_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&requested_processors_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(requested_processors_));
}

Job_gang::~Job_gang() {
  // @@protoc_insertion_point(destructor:Message.protobuf.Job_gang)
  SharedDtor();
}

void Job_gang::SharedDtor() {
  job_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Job_gang::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Job_gang::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Job_gang& Job_gang::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_Job_gang.base);
  return *internal_default_instance();
}


void Job_gang::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  job_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&requested_processors_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(requested_processors_));
  _internal_metadata_.Clear();
}

bool Job_gang::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.Job_gang)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 job_id = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 requested_processors = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &requested_processors_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string job_path = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_job_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->job_path().data(), static_cast<int>(this->job_path().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.protobuf.Job_gang.job_path"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.Job_gang)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.Job_gang)
  return false;
#undef DO_
}

void Job_gang::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 job_id = 9;
  if (this->job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->job_id(), output);
  }

  // int32 requested_processors = 10;
  if (this->requested_processors() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->requested_processors(), output);
  }

  // string job_path = 11;
  if (this->job_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->job_path().data(), static_cast<int>(this->job_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Job_gang.job_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->job_path(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.Job_gang)
}

::google::protobuf::uint8* Job_gang::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 job_id = 9;
  if (this->job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->job_id(), target);
  }

  // int32 requested_processors = 10;
  if (this->requested_processors() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->requested_processors(), target);
  }

  // string job_path = 11;
  if (this->job_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->job_path().data(), static_cast<int>(this->job_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Job_gang.job_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->job_path(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.Job_gang)
  return target;
}

size_t Job_gang::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.Job_gang)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string job_path = 11;
  if (this->job_path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->job_path());
  }

  // int32 job_id = 9;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->job_id());
  }

  // int32 requested_processors = 10;
  if (this->requested_processors() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->requested_processors());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Job_gang::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.Job_gang)
  GOOGLE_DCHECK_NE(&from, this);
  const Job_gang* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Job_gang>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.Job_gang)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.Job_gang)
    MergeFrom(*source);
  }
}

void Job_gang::MergeFrom(const Job_gang& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.Job_gang)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.job_path().size() > 0) {

    job_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.job_path_);
  }
  if (from.job_id() != 0) {
    set_job_id(from.job_id());
  }
  if (from.requested_processors() != 0) {
    set_requested_processors(from.requested_processors());
  }
}

void Job_gang::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.Job_gang)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Job_gang::CopyFrom(const Job_gang& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.Job_gang)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Job_gang::IsInitialized() const {
  return true;
}

void Job_gang::Swap(Job_gang* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Job_gang::InternalSwap(Job_gang* other) {
  using std::swap;
  job_path_.Swap(&other->job_path_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(job_id_, other->job_id_);
  swap(requested_processors_, other->requested_processors_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Job_gang::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace Message
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::schedule* Arena::CreateMaybeMessage< ::Message::protobuf::schedule >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::schedule >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::tasks_set_pro_cpu* Arena::CreateMaybeMessage< ::Message::protobuf::tasks_set_pro_cpu >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::tasks_set_pro_cpu >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::task* Arena::CreateMaybeMessage< ::Message::protobuf::task >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::task >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::start_time* Arena::CreateMaybeMessage< ::Message::protobuf::start_time >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::start_time >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::Job_gang* Arena::CreateMaybeMessage< ::Message::protobuf::Job_gang >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::Job_gang >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
