// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MESSAGES/message.proto

#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_MESSAGES_2fmessage_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_MESSAGES_2fmessage_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Job_gang;
}  // namespace protobuf_MESSAGES_2fmessage_2eproto
namespace Message {
namespace protobuf {
class SchedulingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Scheduling>
      _instance;
} _Scheduling_default_instance_;
class Job_gangDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Job_gang>
      _instance;
} _Job_gang_default_instance_;
class Message_from_LocalDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Message_from_Local>
      _instance;
} _Message_from_Local_default_instance_;
}  // namespace protobuf
}  // namespace Message
namespace protobuf_MESSAGES_2fmessage_2eproto {
static void InitDefaultsScheduling() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_Scheduling_default_instance_;
    new (ptr) ::Message::protobuf::Scheduling();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::Scheduling::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Scheduling =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsScheduling}, {
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_Job_gang.base,}};

static void InitDefaultsJob_gang() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_Job_gang_default_instance_;
    new (ptr) ::Message::protobuf::Job_gang();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::Job_gang::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Job_gang =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsJob_gang}, {}};

static void InitDefaultsMessage_from_Local() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::Message::protobuf::_Message_from_Local_default_instance_;
    new (ptr) ::Message::protobuf::Message_from_Local();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::Message::protobuf::Message_from_Local::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Message_from_Local =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsMessage_from_Local}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Scheduling.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Job_gang.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Message_from_Local.base);
}

::google::protobuf::Metadata file_level_metadata[3];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Scheduling, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Scheduling, tasks_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Scheduling, local_id_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, requested_processors_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Job_gang, job_path_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Message_from_Local, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Message_from_Local, job_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Message_from_Local, local_id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::Message::protobuf::Message_from_Local, status_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Message::protobuf::Scheduling)},
  { 7, -1, sizeof(::Message::protobuf::Job_gang)},
  { 15, -1, sizeof(::Message::protobuf::Message_from_Local)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_Scheduling_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_Job_gang_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::Message::protobuf::_Message_from_Local_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "MESSAGES/message.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026MESSAGES/message.proto\022\020Message.protob"
      "uf\"I\n\nScheduling\022)\n\005tasks\030\001 \003(\0132\032.Messag"
      "e.protobuf.Job_gang\022\020\n\010local_id\030\002 \001(\005\"J\n"
      "\010Job_gang\022\016\n\006job_id\030\010 \001(\005\022\034\n\024requested_p"
      "rocessors\030\003 \001(\005\022\020\n\010job_path\030\004 \001(\t\"F\n\022Mes"
      "sage_from_Local\022\016\n\006job_id\030\005 \001(\005\022\020\n\010local"
      "_id\030\006 \001(\005\022\016\n\006status\030\007 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 273);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MESSAGES/message.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MESSAGES_2fmessage_2eproto
namespace Message {
namespace protobuf {

// ===================================================================

void Scheduling::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Scheduling::kTasksFieldNumber;
const int Scheduling::kLocalIdFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Scheduling::Scheduling()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_Scheduling.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.Scheduling)
}
Scheduling::Scheduling(const Scheduling& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      tasks_(from.tasks_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  local_id_ = from.local_id_;
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.Scheduling)
}

void Scheduling::SharedCtor() {
  local_id_ = 0;
}

Scheduling::~Scheduling() {
  // @@protoc_insertion_point(destructor:Message.protobuf.Scheduling)
  SharedDtor();
}

void Scheduling::SharedDtor() {
}

void Scheduling::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Scheduling::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Scheduling& Scheduling::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_Scheduling.base);
  return *internal_default_instance();
}


void Scheduling::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.Scheduling)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  tasks_.Clear();
  local_id_ = 0;
  _internal_metadata_.Clear();
}

bool Scheduling::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.Scheduling)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .Message.protobuf.Job_gang tasks = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_tasks()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 local_id = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &local_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.Scheduling)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.Scheduling)
  return false;
#undef DO_
}

void Scheduling::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.Scheduling)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.Job_gang tasks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasks_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->tasks(static_cast<int>(i)),
      output);
  }

  // int32 local_id = 2;
  if (this->local_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->local_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.Scheduling)
}

::google::protobuf::uint8* Scheduling::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.Scheduling)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .Message.protobuf.Job_gang tasks = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->tasks_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->tasks(static_cast<int>(i)), deterministic, target);
  }

  // int32 local_id = 2;
  if (this->local_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->local_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.Scheduling)
  return target;
}

size_t Scheduling::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.Scheduling)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .Message.protobuf.Job_gang tasks = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->tasks_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->tasks(static_cast<int>(i)));
    }
  }

  // int32 local_id = 2;
  if (this->local_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->local_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Scheduling::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.Scheduling)
  GOOGLE_DCHECK_NE(&from, this);
  const Scheduling* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Scheduling>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.Scheduling)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.Scheduling)
    MergeFrom(*source);
  }
}

void Scheduling::MergeFrom(const Scheduling& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.Scheduling)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  tasks_.MergeFrom(from.tasks_);
  if (from.local_id() != 0) {
    set_local_id(from.local_id());
  }
}

void Scheduling::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.Scheduling)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Scheduling::CopyFrom(const Scheduling& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.Scheduling)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Scheduling::IsInitialized() const {
  return true;
}

void Scheduling::Swap(Scheduling* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Scheduling::InternalSwap(Scheduling* other) {
  using std::swap;
  CastToBase(&tasks_)->InternalSwap(CastToBase(&other->tasks_));
  swap(local_id_, other->local_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Scheduling::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Job_gang::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Job_gang::kJobIdFieldNumber;
const int Job_gang::kRequestedProcessorsFieldNumber;
const int Job_gang::kJobPathFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Job_gang::Job_gang()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_Job_gang.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.Job_gang)
}
Job_gang::Job_gang(const Job_gang& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  job_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.job_path().size() > 0) {
    job_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.job_path_);
  }
  ::memcpy(&requested_processors_, &from.requested_processors_,
    static_cast<size_t>(reinterpret_cast<char*>(&job_id_) -
    reinterpret_cast<char*>(&requested_processors_)) + sizeof(job_id_));
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.Job_gang)
}

void Job_gang::SharedCtor() {
  job_path_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&requested_processors_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&job_id_) -
      reinterpret_cast<char*>(&requested_processors_)) + sizeof(job_id_));
}

Job_gang::~Job_gang() {
  // @@protoc_insertion_point(destructor:Message.protobuf.Job_gang)
  SharedDtor();
}

void Job_gang::SharedDtor() {
  job_path_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Job_gang::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Job_gang::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Job_gang& Job_gang::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_Job_gang.base);
  return *internal_default_instance();
}


void Job_gang::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  job_path_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&requested_processors_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&job_id_) -
      reinterpret_cast<char*>(&requested_processors_)) + sizeof(job_id_));
  _internal_metadata_.Clear();
}

bool Job_gang::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.Job_gang)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 requested_processors = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &requested_processors_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string job_path = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_job_path()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->job_path().data(), static_cast<int>(this->job_path().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.protobuf.Job_gang.job_path"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 job_id = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.Job_gang)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.Job_gang)
  return false;
#undef DO_
}

void Job_gang::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requested_processors = 3;
  if (this->requested_processors() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->requested_processors(), output);
  }

  // string job_path = 4;
  if (this->job_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->job_path().data(), static_cast<int>(this->job_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Job_gang.job_path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->job_path(), output);
  }

  // int32 job_id = 8;
  if (this->job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->job_id(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.Job_gang)
}

::google::protobuf::uint8* Job_gang::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.Job_gang)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 requested_processors = 3;
  if (this->requested_processors() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->requested_processors(), target);
  }

  // string job_path = 4;
  if (this->job_path().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->job_path().data(), static_cast<int>(this->job_path().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Job_gang.job_path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->job_path(), target);
  }

  // int32 job_id = 8;
  if (this->job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->job_id(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.Job_gang)
  return target;
}

size_t Job_gang::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.Job_gang)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string job_path = 4;
  if (this->job_path().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->job_path());
  }

  // int32 requested_processors = 3;
  if (this->requested_processors() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->requested_processors());
  }

  // int32 job_id = 8;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->job_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Job_gang::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.Job_gang)
  GOOGLE_DCHECK_NE(&from, this);
  const Job_gang* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Job_gang>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.Job_gang)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.Job_gang)
    MergeFrom(*source);
  }
}

void Job_gang::MergeFrom(const Job_gang& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.Job_gang)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.job_path().size() > 0) {

    job_path_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.job_path_);
  }
  if (from.requested_processors() != 0) {
    set_requested_processors(from.requested_processors());
  }
  if (from.job_id() != 0) {
    set_job_id(from.job_id());
  }
}

void Job_gang::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.Job_gang)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Job_gang::CopyFrom(const Job_gang& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.Job_gang)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Job_gang::IsInitialized() const {
  return true;
}

void Job_gang::Swap(Job_gang* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Job_gang::InternalSwap(Job_gang* other) {
  using std::swap;
  job_path_.Swap(&other->job_path_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(requested_processors_, other->requested_processors_);
  swap(job_id_, other->job_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Job_gang::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Message_from_Local::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Message_from_Local::kJobIdFieldNumber;
const int Message_from_Local::kLocalIdFieldNumber;
const int Message_from_Local::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Message_from_Local::Message_from_Local()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_MESSAGES_2fmessage_2eproto::scc_info_Message_from_Local.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:Message.protobuf.Message_from_Local)
}
Message_from_Local::Message_from_Local(const Message_from_Local& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.status().size() > 0) {
    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
  ::memcpy(&job_id_, &from.job_id_,
    static_cast<size_t>(reinterpret_cast<char*>(&local_id_) -
    reinterpret_cast<char*>(&job_id_)) + sizeof(local_id_));
  // @@protoc_insertion_point(copy_constructor:Message.protobuf.Message_from_Local)
}

void Message_from_Local::SharedCtor() {
  status_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&local_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(local_id_));
}

Message_from_Local::~Message_from_Local() {
  // @@protoc_insertion_point(destructor:Message.protobuf.Message_from_Local)
  SharedDtor();
}

void Message_from_Local::SharedDtor() {
  status_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Message_from_Local::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Message_from_Local::descriptor() {
  ::protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Message_from_Local& Message_from_Local::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_MESSAGES_2fmessage_2eproto::scc_info_Message_from_Local.base);
  return *internal_default_instance();
}


void Message_from_Local::Clear() {
// @@protoc_insertion_point(message_clear_start:Message.protobuf.Message_from_Local)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&job_id_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&local_id_) -
      reinterpret_cast<char*>(&job_id_)) + sizeof(local_id_));
  _internal_metadata_.Clear();
}

bool Message_from_Local::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Message.protobuf.Message_from_Local)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 job_id = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &job_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 local_id = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &local_id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string status = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_status()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->status().data(), static_cast<int>(this->status().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Message.protobuf.Message_from_Local.status"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Message.protobuf.Message_from_Local)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Message.protobuf.Message_from_Local)
  return false;
#undef DO_
}

void Message_from_Local::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Message.protobuf.Message_from_Local)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 job_id = 5;
  if (this->job_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->job_id(), output);
  }

  // int32 local_id = 6;
  if (this->local_id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->local_id(), output);
  }

  // string status = 7;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Message_from_Local.status");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->status(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:Message.protobuf.Message_from_Local)
}

::google::protobuf::uint8* Message_from_Local::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:Message.protobuf.Message_from_Local)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 job_id = 5;
  if (this->job_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->job_id(), target);
  }

  // int32 local_id = 6;
  if (this->local_id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->local_id(), target);
  }

  // string status = 7;
  if (this->status().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->status().data(), static_cast<int>(this->status().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Message.protobuf.Message_from_Local.status");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->status(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Message.protobuf.Message_from_Local)
  return target;
}

size_t Message_from_Local::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Message.protobuf.Message_from_Local)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string status = 7;
  if (this->status().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->status());
  }

  // int32 job_id = 5;
  if (this->job_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->job_id());
  }

  // int32 local_id = 6;
  if (this->local_id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->local_id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Message_from_Local::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Message.protobuf.Message_from_Local)
  GOOGLE_DCHECK_NE(&from, this);
  const Message_from_Local* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Message_from_Local>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Message.protobuf.Message_from_Local)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Message.protobuf.Message_from_Local)
    MergeFrom(*source);
  }
}

void Message_from_Local::MergeFrom(const Message_from_Local& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Message.protobuf.Message_from_Local)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.status().size() > 0) {

    status_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.status_);
  }
  if (from.job_id() != 0) {
    set_job_id(from.job_id());
  }
  if (from.local_id() != 0) {
    set_local_id(from.local_id());
  }
}

void Message_from_Local::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Message.protobuf.Message_from_Local)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Message_from_Local::CopyFrom(const Message_from_Local& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Message.protobuf.Message_from_Local)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Message_from_Local::IsInitialized() const {
  return true;
}

void Message_from_Local::Swap(Message_from_Local* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Message_from_Local::InternalSwap(Message_from_Local* other) {
  using std::swap;
  status_.Swap(&other->status_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(job_id_, other->job_id_);
  swap(local_id_, other->local_id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Message_from_Local::GetMetadata() const {
  protobuf_MESSAGES_2fmessage_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MESSAGES_2fmessage_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace protobuf
}  // namespace Message
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::Scheduling* Arena::CreateMaybeMessage< ::Message::protobuf::Scheduling >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::Scheduling >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::Job_gang* Arena::CreateMaybeMessage< ::Message::protobuf::Job_gang >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::Job_gang >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::Message::protobuf::Message_from_Local* Arena::CreateMaybeMessage< ::Message::protobuf::Message_from_Local >(Arena* arena) {
  return Arena::CreateInternal< ::Message::protobuf::Message_from_Local >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
